### ISSUE TITLE
Admin page Tracking scope tab summaries not updating

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/matomo#16]
**Steps to reproduce**

1. Install matomo module
2. Navigate to admin page
3. Modify settings under tracking scope

**Expected result**
Summaries in each vertical tab update to reflect the setting changes

**Actual result**
Summaries do not change for Domains, Pages, Roles (partial), Users, Links and downloads, Search, Privacy.  The checkboxes for Roles do and Messages do
![QHVRV6Vipc](https://user-images.githubusercontent.com/20357797/148969329-989786b7-b542-4fb6-95d3-7b33f0246ede.gif)

Cause: several input names in the matomo.admin.js file are incorrect: include matomo in structure when this is not there.  Pull request to follow.

**Comment by indigoxela** [comment]
Nice catch! :+1:  I use Matomo for quite some time now, but I never realized, that the summaries in the vertical tabs aren't properly working.

**Comment by indigoxela** [comment]
@yorkshire-pudding many thanks for your PR, merged.

It's probably time for a new release, it's been a while.
