### ISSUE TITLE
PHP 8 Deprecated function: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in matomo_preprocess_page() (line 111 of matomo.module).

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/matomo#34]
**Steps to reproduce**

1. Enable in site on 8.1
2. View status report before site is configured.

**Actual result**
Deprecated function: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in matomo_preprocess_page() (line 111 of /app/docroot/modules/contrib/matomo/matomo.module).

Also get this:
Deprecated function: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in matomo_requirements() (line 46 of /app/docroot/modules/contrib/matomo/matomo.install).

**Expected result**
no deprecation notices

**Comment by indigoxela** [comment]
Ah, I get it, many thanks for reporting @yorkshire-pudding :+1:

**Comment by indigoxela** [comment]
Hm, there must be some additional step to reproduce it...

The config is saved, as soon as the module gets enabled. And from that point param 2 (site_id) is an empty string, but not null. How can it be null after enabling the module?

**Comment by yorkshire-pudding** [comment]
Interestingly before I saw your comments here I was wondering whether it might be specific to my scenario.  I imported the database before the config.  Let me see if I can reproduce it; if it is my scenario then it really isn't a bug as those conditions are not normal.

**Comment by yorkshire-pudding** [comment]
I haven't been able to reproduce normally so I think the module does enough to mean that this will never normally occur.
