### ISSUE TITLE
Variable last_cache should be stored in state

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/matomo#39]
The variable `last_cache` should be handled with `state_set` and `state_get`, not config. It gets updated on cron runs (`matomo_cron`) and can put the config out of sync between live and staging.

There's a similar variable in the googleanalytics module: `googleanalytics_last_cache` which *is* stored in state.

**Comment by herbdool** [comment]
@hosef, @indigoxela I've created a PR for this bug. Thanks.

**Comment by indigoxela** [comment]
@herbdool nice catch, this should be a state, not config.

Small suggestion to remove the obsolete config save, but looks good otherwise. :+1:

**Comment by herbdool** [comment]
@indigoxela I've fixed that.

**Comment by indigoxela** [comment]
@herbdool many thanks, merged. :+1:
